### ISSUE TITLE
[DM Request]: file - metadata error

### ISSUE THREAD

**Issue by kwittmeyer** [ranchobiosciences/Data_Modeling_Issues_Templates#253]
### Description of changes

[workbook-5.xlsx](https://github.com/ranchobiosciences/Data_Modeling_Issues_Templates/files/10850936/workbook-5.xlsx)

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `INFO` Workbook downloaded
Successfully saved on the server

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `INFO` Workbook format valid
Submitter workbook has the supported file extension

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `ERROR` Old workbook submitted
The version of submitted workbook does not match the latest version of workbook

*Next steps:*
1. Download a valid workbook from the main branch of current repository.
2. Apply your changes and save the file.
3. Re-submit updated workbook in a new Issue.

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `ERROR` Submitted issue is outdated
Either your issue is not the latest one submitted or the remote repository has been updated after your issue creation.

*Next steps:*
1. Download a valid workbook from the main branch of current repository.
2. Apply your changes and save the file.
3. Re-submit updated workbook in a new Issue.

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `ERROR` Submitted issue is outdated
Either your issue is not the latest one submitted or the remote repository has been updated after your issue creation.

*Next steps:*
1. Download a valid workbook from the main branch of current repository.
2. Apply your changes and save the file.
3. Re-submit updated workbook in a new Issue.

**Comment by max-kastsiuchenka-ranchobiosciences** [comment]
### `ERROR` Submitted issue is outdated
Either your issue is not the latest one submitted or the remote repository has been updated after your issue creation.

*Next steps:*
1. Download a valid workbook from the main branch of current repository.
2. Apply your changes and save the file.
3. Re-submit updated workbook in a new Issue.
